import { useState } from 'react';
import { Button } from '../../components/ui/Button';

interface Collector {
    id: number;
    name: string;
    branch: string;
    collections: number;
    revenue: string;
    performance: number;
    status: 'Active' | 'Inactive';
    zone: string;
    phone: string;
    email: string;
    lastCollection: string;
}

export function Collectors() {
    const [collectors] = useState<Collector[]>([
        {
            id: 1,
            name: 'Jean Dupont',
            branch: 'Downtown Branch',
            zone: 'Centre Douala',
            phone: '+237 670-123-456',
            email: 'jean.dupont@procollector.com',
            collections: 45,
            revenue: 'FCFA 125,000',
            performance: 92,
            status: 'Active',
            lastCollection: '2 hours ago'
        },
        {
            id: 2,
            name: 'Marie Smith',
            branch: 'North District',
            zone: 'Bonanjo, Douala',
            phone: '+237 671-234-567',
            email: 'marie.smith@procollector.com',
            collections: 38,
            revenue: 'FCFA 98,000',
            performance: 88,
            status: 'Active',
            lastCollection: '4 hours ago'
        },
        {
            id: 3,
            name: 'Paul Biya',
            branch: 'East Side',
            zone: 'Akwa, Douala',
            phone: '+237 672-345-678',
            email: 'paul.biya@procollector.com',
            collections: 22,
            revenue: 'FCFA 65,000',
            performance: 75,
            status: 'Inactive',
            lastCollection: '1 day ago'
        },
        {
            id: 4,
            name: 'Sarah Ngono',
            branch: 'South Branch',
            zone: 'Bastos, Yaoundé',
            phone: '+237 673-456-789',
            email: 'sarah.ngono@procollector.com',
            collections: 56,
            revenue: 'FCFA 145,000',
            performance: 95,
            status: 'Active',
            lastCollection: '1 hour ago'
        },
        {
            id: 5,
            name: 'Pierre Mboh',
            branch: 'West District',
            zone: 'Messa, Yaoundé',
            phone: '+237 674-567-890',
            email: 'pierre.mboh@procollector.com',
            collections: 12,
            revenue: 'FCFA 35,000',
            performance: 65,
            status: 'Inactive',
            lastCollection: '3 days ago'
        }
    ]);

    const [generatingReport, setGeneratingReport] = useState<number | null>(null);

    const handleGenerateReport = async (collectorId: number) => {
        setGeneratingReport(collectorId);
        try {
            // Simulate API call delay
            await new Promise(resolve => setTimeout(resolve, 2000));

            // Create a simple report
            const collector = collectors.find(c => c.id === collectorId);
            if (!collector) return;

            const reportData = {
                collectorName: collector.name,
                branch: collector.branch,
                zone: collector.zone,
                period: 'Last 30 days',
                totalCollections: collector.collections,
                totalRevenue: collector.revenue,
                performance: collector.performance,
                status: collector.status,
                generatedAt: new Date().toLocaleString()
            };

            // Create and download the report
            const reportContent = `
COLLECTOR PERFORMANCE REPORT
===========================

Collector Details:
- Name: ${reportData.collectorName}
- Branch: ${reportData.branch}
- Zone: ${reportData.zone}
- Status: ${reportData.status}

Performance Summary (${reportData.period}):
- Total Collections: ${reportData.totalCollections}
- Total Revenue: ${reportData.totalRevenue}
- Performance Rating: ${reportData.performance}%

Report Generated: ${reportData.generatedAt}

Generated by ProCollector Management System
            `;

            const blob = new Blob([reportContent], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `${collector.name.replace(' ', '_')}_Report_${new Date().toISOString().split('T')[0]}.txt`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);

        } catch (error) {
            console.error('Failed to generate report:', error);
            alert('Failed to generate report. Please try again.');
        } finally {
            setGeneratingReport(null);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-semibold">Collector Management</h2>
                    <p>Manage collectors, track performance, and generate reports</p>
                </div>
                <Button
                    variant="primary"
                    onClick={() => {
                        // Generate summary report for all collectors
                        const summaryReport = collectors.map(c =>
                            `${c.name} (${c.branch}): ${c.collections} collections, ${c.revenue}, ${c.performance}% performance`
                        ).join('\n');

                        const blob = new Blob([summaryReport], { type: 'text/plain' });
                        const url = URL.createObjectURL(blob);
                        const link = document.createElement('a');
                        link.href = url;
                        link.download = `All_Collectors_Report_${new Date().toISOString().split('T')[0]}.txt`;
                        document.body.appendChild(link);
                        link.click();
                        document.body.removeChild(link);
                        URL.revokeObjectURL(url);
                    }}
                    className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded border-0"
                >
                    Generate Summary Report
                </Button>
            </div>

            <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
                <table className="w-full">
                    <thead className="bg-gray-50 border-b border-gray-200">
                        <tr>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Collector</th>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Branch</th>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Collections</th>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Revenue</th>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Performance</th>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Status</th>
                            <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                        {collectors.map((collector) => (
                            <tr key={collector.id} className="hover:bg-gray-50">
                                <td className="px-4 py-4">
                                    <div>
                                        <div className="font-medium text-gray-900">{collector.name}</div>
                                        <div className="text-sm text-gray-500">{collector.zone}</div>
                                        <div className="text-sm text-gray-500">{collector.phone}</div>
                                    </div>
                                </td>
                                <td className="px-4 py-4 text-sm text-gray-900">{collector.branch}</td>
                                <td className="px-4 py-4 text-sm text-gray-900">{collector.collections}</td>
                                <td className="px-4 py-4 text-sm font-medium text-gray-900">{collector.revenue}</td>
                                <td className="px-4 py-4">
                                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                                        collector.performance >= 90 ? 'bg-green-100 text-green-800' :
                                        collector.performance >= 80 ? 'bg-yellow-100 text-yellow-800' :
                                        'bg-red-100 text-red-800'
                                    }`}>
                                        {collector.performance}%
                                    </span>
                                </td>
                                <td className="px-4 py-4">
                                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                                        collector.status === 'Active' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                                    }`}>
                                        {collector.status}
                                    </span>
                                </td>
                                <td className="px-4 py-4">
                                    <div className="flex gap-2">
                                        <button className="px-3 py-1 text-sm border border-gray-300 rounded text-gray-700 hover:bg-gray-50">
                                            View Details
                                        </button>
                                        <button
                                            onClick={() => handleGenerateReport(collector.id)}
                                            disabled={generatingReport === collector.id}
                                            className="px-3 py-1 text-sm bg-blue-600 text-white border border-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                                        >
                                            {generatingReport === collector.id ? 'Generating...' : 'Generate Report'}
                                        </button>
                                        <button className="px-3 py-1 text-sm border border-gray-300 rounded text-gray-700 hover:bg-gray-50">
                                            Track Performance
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}