// No external imports needed for this classic design

export function Reports() {
    const handleExportPDF = async () => {
        // Generate simple PDF content
        const reportData = `
ORGANIZATION ANALYTICS REPORT
Generated: ${new Date().toLocaleString()}

PERFORMANCE METRICS:
- Average Collection: FCFA 12,450
- Active Agents: 156
- Compliance Rate: 98.2%
- Market Fees: FCFA 45M

REGIONAL PERFORMANCE:
- Littoral (Douala): 75%
- Centre (Yaoundé): 62%
- West (Bafoussam): 45%
- South (Kribi): 28%

COLLECTION TRENDS (Last 7 days):
- Monday: FCFA 40M
- Tuesday: FCFA 70M
- Wednesday: FCFA 45M
- Thursday: FCFA 90M
- Friday: FCFA 65M
- Saturday: FCFA 80M
- Sunday: FCFA 55M

Generated by ProCollector Analytics System
        `;

        const blob = new Blob([reportData], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `organization_report_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const handleExportExcel = async () => {
        // Generate simple CSV content
        const csvData = `Metric,Value,Change
Average Collection,FCFA 12,450,+12%
Active Agents,156,+4
Compliance Rate,98.2%,-0.5%
Market Fees,FCFA 45M,+18%
Littoral Performance,75%,-
Centre Performance,62%,-
West Performance,45%,-
South Performance,28%,-`;

        const blob = new Blob([csvData], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `organization_report_${new Date().toISOString().split('T')[0]}.csv`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-semibold">Organization Reports</h2>
                    <p className="text-sm text-gray-600">Collection performance and analytics overview</p>
                </div>
                <div className="flex gap-2">
                    <button onClick={handleExportPDF} className="px-4 py-2 bg-blue-600 text-white border border-blue-600 rounded hover:bg-blue-700 text-sm font-medium">
                        Export PDF
                    </button>
                    <button onClick={handleExportExcel} className="px-4 py-2 bg-green-600 text-white border border-green-600 rounded hover:bg-green-700 text-sm font-medium">
                        Export Excel
                    </button>
                </div>
            </div>

            {/* Summary Cards */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="bg-white border border-gray-200 rounded-lg p-4">
                    <div className="text-sm text-gray-600 mb-1">Average Collection</div>
                    <div className="text-2xl font-bold text-blue-600">FCFA 12,450</div>
                    <div className="text-xs text-green-600 mt-1">+12% from last month</div>
                </div>
                <div className="bg-white border border-gray-200 rounded-lg p-4">
                    <div className="text-sm text-gray-600 mb-1">Active Agents</div>
                    <div className="text-2xl font-bold text-green-600">156</div>
                    <div className="text-xs text-green-600 mt-1">+4 this week</div>
                </div>
                <div className="bg-white border border-gray-200 rounded-lg p-4">
                    <div className="text-sm text-gray-600 mb-1">Compliance Rate</div>
                    <div className="text-2xl font-bold text-purple-600">98.2%</div>
                    <div className="text-xs text-red-600 mt-1">-0.5% this month</div>
                </div>
                <div className="bg-white border border-gray-200 rounded-lg p-4">
                    <div className="text-sm text-gray-600 mb-1">Total Revenue</div>
                    <div className="text-2xl font-bold text-orange-600">FCFA 45M</div>
                    <div className="text-xs text-green-600 mt-1">+18% this quarter</div>
                </div>
            </div>

            {/* Regional Performance */}
            <div className="bg-white border border-gray-200 rounded-lg p-4">
                <h3 className="text-lg font-semibold mb-4">Collection by Region</h3>
                <div className="space-y-4">
                    {[
                        { name: 'Littoral (Douala)', value: 75, collections: 'FCFA 18.2M' },
                        { name: 'Centre (Yaoundé)', value: 62, collections: 'FCFA 14.8M' },
                        { name: 'West (Bafoussam)', value: 45, collections: 'FCFA 10.9M' },
                        { name: 'South (Kribi)', value: 28, collections: 'FCFA 6.7M' },
                    ].map((region) => (
                        <div key={region.name} className="space-y-2">
                            <div className="flex justify-between text-sm">
                                <span className="font-medium">{region.name}</span>
                                <span className="font-semibold">{region.collections}</span>
                            </div>
                            <div className="w-full bg-gray-200 rounded-full h-2">
                                <div
                                    className="bg-blue-600 h-2 rounded-full"
                                    style={{ width: `${region.value}%` }}
                                ></div>
                            </div>
                            <div className="text-xs text-gray-600 text-right">{region.value}% performance</div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Weekly Trends */}
            <div className="bg-white border border-gray-200 rounded-lg p-4">
                <h3 className="text-lg font-semibold mb-4">Weekly Collection Trends</h3>
                <div className="grid grid-cols-7 gap-4">
                    {[
                        { day: 'Mon', value: 40, amount: 'FCFA 12M' },
                        { day: 'Tue', value: 70, amount: 'FCFA 21M' },
                        { day: 'Wed', value: 45, amount: 'FCFA 13.5M' },
                        { day: 'Thu', value: 90, amount: 'FCFA 27M' },
                        { day: 'Fri', value: 65, amount: 'FCFA 19.5M' },
                        { day: 'Sat', value: 80, amount: 'FCFA 24M' },
                        { day: 'Sun', value: 55, amount: 'FCFA 16.5M' }
                    ].map((day) => (
                        <div key={day.day} className="text-center">
                            <div className="text-xs text-gray-600 mb-1">{day.day}</div>
                            <div className="w-full bg-gray-200 rounded-full h-16 flex items-end justify-center mb-1">
                                <div
                                    className="w-8 bg-blue-600 rounded-t"
                                    style={{ height: `${day.value}%` }}
                                ></div>
                            </div>
                            <div className="text-xs font-medium">{day.amount}</div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
